project:
  type: website
  preview:
    port: 4243
  resources:
    - objects.txt
  output-dir: ../../docs/py

website:
  title: "shinychat"
  site-url: https://posit-dev.github.io/shinychat/py
  description: Chat UI Component for Shiny

  bread-crumbs: true
  open-graph: true
  twitter-card: true

  repo-url: https://github.com/posit-dev/shinychat/
  repo-actions: [issue, edit]
  repo-subdir: pkg-py/docs

  page-footer:
    left: |
      Proudly supported by
      [![](https://posit.co/wp-content/uploads/2024/06/Posit-Logos-2024_horiz-full-color.svg){fig-alt="Posit" width=65px}](https://posit.co)

  navbar:
    left:
      - text: Get Started
        href: index.qmd
      - text: API Reference
        href: api/index.qmd
    tools:
      - icon: github
        menu:
          - text: Source code
            href:  https://github.com/posit-dev/shinychat/pkg-py
          - text: Report a bug
            href:  https://github.com/posit-dev/shinychat/issues/new

format:
  html:
    theme: [brand]
    highlight-style: github
    toc: true

lightbox: auto

metadata-files:
  - _sidebar-python.yml

quartodoc:
  package: shinychat
  dir: api
  sidebar: _sidebar-python.yml
  title: shinychat Reference
  out_index: index.qmd
  render_interlinks: true
  rewrite_all_pages: true
  sections:
    - title: Shiny Core
      options:
        signature_name: relative
        include_imports: false
        include_inherited: false
        include_attributes: true
        include_classes: true
        include_functions: true
      contents:
        - Chat
        - chat_ui
    - title: Shiny Express
      options:
        signature_name: relative
        include_imports: false
        include_inherited: true
        include_attributes: true
        include_classes: true
        include_functions: true
      contents:
        - express.Chat
    - title: Testing
      options:
        signature_name: relative
        include_imports: false
        include_inherited: false
        include_attributes: true
        include_classes: true
        include_functions: true
      contents:
        - playwright.ChatController

interlinks:
  fast: true
  sources:
    pydantic:
      url: https://docs.pydantic.dev/latest/
    python:
      url: https://docs.python.org/3/

editor:
  render-on-save: true
  markdown:
    canonical: true
    wrap: sentence
