# playwright.ChatController { #shinychat.playwright.ChatController }

```python
playwright.ChatController(page, id)
```

Controller for :func:`shiny.ui.chat`.

## Attributes

| Name | Description |
| --- | --- |
| [loc](#shinychat.playwright.ChatController.loc) | Playwright `Locator` for the chat. |
| [loc_input](#shinychat.playwright.ChatController.loc_input) | Playwright `Locator` for the chat's <textarea> input. |
| [loc_input_button](#shinychat.playwright.ChatController.loc_input_button) | Playwright `Locator` for the chat's <button> input. |
| [loc_input_container](#shinychat.playwright.ChatController.loc_input_container) | Playwright `Locator` for the chat input container. |
| [loc_latest_message](#shinychat.playwright.ChatController.loc_latest_message) | Playwright `Locator` for the last message in the chat. |
| [loc_messages](#shinychat.playwright.ChatController.loc_messages) | Playwright `Locator` for the chat messages. |

## Methods

| Name | Description |
| --- | --- |
| [expect_latest_message](#shinychat.playwright.ChatController.expect_latest_message) | Expects the last message in the chat. |
| [expect_messages](#shinychat.playwright.ChatController.expect_messages) | Expects the chat messages. |
| [expect_user_input](#shinychat.playwright.ChatController.expect_user_input) | Expects the user message in the chat. |
| [send_user_input](#shinychat.playwright.ChatController.send_user_input) | Sends the user message in the chat. |
| [set_user_input](#shinychat.playwright.ChatController.set_user_input) | Sets the user message in the chat. |

### expect_latest_message { #shinychat.playwright.ChatController.expect_latest_message }

```python
playwright.ChatController.expect_latest_message(value, *, timeout=None)
```

Expects the last message in the chat.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                                                   | Description                                                               | Default    |
|---------|--------------------------------------------------------|---------------------------------------------------------------------------|------------|
| value   | [PatternOrStr](`shiny.playwright._types.PatternOrStr`) | The expected last message.                                                | _required_ |
| timeout | [Timeout](`shiny.playwright._types.Timeout`)           | The maximum time to wait for the expectation to pass. Defaults to `None`. | `None`     |

### expect_messages { #shinychat.playwright.ChatController.expect_messages }

```python
playwright.ChatController.expect_messages(value, *, timeout=None)
```

Expects the chat messages.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                                                   | Description                                                               | Default    |
|---------|--------------------------------------------------------|---------------------------------------------------------------------------|------------|
| value   | [PatternOrStr](`shiny.playwright._types.PatternOrStr`) | The expected messages.                                                    | _required_ |
| timeout | [Timeout](`shiny.playwright._types.Timeout`)           | The maximum time to wait for the expectation to pass. Defaults to `None`. | `None`     |

### expect_user_input { #shinychat.playwright.ChatController.expect_user_input }

```python
playwright.ChatController.expect_user_input(value, *, timeout=None)
```

Expects the user message in the chat.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                                                   | Description                                                               | Default    |
|---------|--------------------------------------------------------|---------------------------------------------------------------------------|------------|
| value   | [PatternOrStr](`shiny.playwright._types.PatternOrStr`) | The expected user message.                                                | _required_ |
| timeout | [Timeout](`shiny.playwright._types.Timeout`)           | The maximum time to wait for the expectation to pass. Defaults to `None`. | `None`     |

### send_user_input { #shinychat.playwright.ChatController.send_user_input }

```python
playwright.ChatController.send_user_input(method='enter', timeout=None)
```

Sends the user message in the chat.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                                                | Description                                                                                     | Default   |
|---------|-----------------------------------------------------|-------------------------------------------------------------------------------------------------|-----------|
| method  | [Literal](`typing.Literal`)\[\'enter\', \'click\'\] | The method to send the user message. Defaults to `"enter"`.                                     | `'enter'` |
| timeout | [Timeout](`shiny.playwright._types.Timeout`)        | The maximum time to wait for the chat input to be visible and interactable. Defaults to `None`. | `None`    |

### set_user_input { #shinychat.playwright.ChatController.set_user_input }

```python
playwright.ChatController.set_user_input(value, *, timeout=None)
```

Sets the user message in the chat.

#### Parameters {.doc-section .doc-section-parameters}

| Name    | Type                                         | Description                                                                                     | Default    |
|---------|----------------------------------------------|-------------------------------------------------------------------------------------------------|------------|
| value   | [str](`str`)                                 | The message to send.                                                                            | _required_ |
| timeout | [Timeout](`shiny.playwright._types.Timeout`) | The maximum time to wait for the chat input to be visible and interactable. Defaults to `None`. | `None`     |