# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    paths:
      - 'pkg-r/man'
      - 'pkg-r/vignettes'
      - 'pkg-r/pkgdown'
      - '.github/workflows/pkgdown.yaml'
  pull_request:
    paths:
      - 'pkg-r/man'
      - 'pkg-r/vignettes'
      - 'pkg-r/pkgdown'
      - '.github/workflows/pkgdown.yaml'
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions:
  contents: write

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    # Only run on release events for tags start with "r/v*"
    if: github.event_name != 'release' || startsWith(github.ref, 'refs/tags/r/v')

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website
          working-directory: pkg-r

      - name: Build site
        working-directory: pkg-r
        shell: Rscript {0}
        run: pkgdown::build_site()

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
